### ISSUE TITLE
PNG/JPG output?

### ISSUE THREAD

**Issue by dreamonhigh** [benschneider/PyGnuplot#18]
hello, 

is there a way to output as a png or jpg format. ps or pdf I cannot use for web usage.
tried to convert ps to png/jpg but its not usable for this.

maybe its already exportable? but how

Thanks

**Comment by benschneider** [comment]
in gnuplot the command would be something like:

```

set term png nocrop enhanced size 640, 480 font "arial, 12.0"
set out =  "myfile.png"
replot

set term x11
```
