### ISSUE TITLE
xtics newline don't work

### ISSUE THREAD

**Issue by dreamonhigh** [benschneider/PyGnuplot#19]
Hello. 

using : 
`gp.c("set xtics format '%d.%m\n%h'")`

I'm getting a invalid command. cause of \n . normally this works. 
here you can see. 
[https://stackoverflow.com/questions/25763576/gnuplot-how-to-set-new-line-in-xtics-timefmt](url)  

I tried same command with """ """ quoting. no luck. 
what can I do?

Thank you!

**Comment by benschneider** [comment]
yeah I think python interprets those special characters, so you need to escape the escape characters :).
try : "\\n" instead of "\n"

**Comment by dreamonhigh** [comment]
thanks .. but still no luck
using \\n it prints → 06.12.\n12  

using one single \n it result an error. 

full command:     gp.c("set xtics format '%d.%m\\n%HUhr' textcolor 'black'")
one more idea?

**Comment by benschneider** [comment]
does this one work: gp.c(r"set xtics format '%d.%m\n%HUhr' textcolor 'black'")
?

**Comment by dreamonhigh** [comment]
still no luck :(
it through no error. but still no linefeed at this point.

**Comment by dreamonhigh** [comment]
It prints "06.12\n12" as label, no linefeed but \n is printed instead

**Comment by dreamonhigh** [comment]
no more idea?

**Comment by benschneider** [comment]
For the meantime, you could once type them in in gnuplot then use : save 'myfile.gn'.
open "myfile.gn" edit / shorten it to your needs and load that one when needed.

can you please tell me the full command string that you are trying to generate and pass from python to gnuplot?
i.e. example code ?

**Comment by benschneider** [comment]
It might be good to "prepare" the '%d.%m\n%h' string beforehand, i.e. store it in a separate variable, so you can check if python is parsing it right.

**Comment by dreamonhigh** [comment]
sorry. tried a lot of things without luck. here is a easy example.
linefeed is ignored or \n is printed but not done.
example makes no sense, but I'm only interested in \n to linefeed.

import PyGnuplot as gp
gp.c("set title 'XXXXXXXXXXXXXXXXXXXXXXX")
gp.c(r"set xtics format 'Line1\nLine2' textcolor 'black'")
gp.c("plot [-10:10] sin(x),atan(x),cos(atan(x))")

**Comment by benschneider** [comment]
Just running this directly in gnuplot gives me the exact same results as run via PyGnuplot.

So I tried changing the command itself until I got a new line working:
> set xtics format "Line1\nLine2" textcolor "black"

turns out gnuplot requires " marks not ' marks ;).

so your command needs to be:
gp.c("set title 'XXXXXXXXXXXXXXXXXXXXXXX")
gp.c(r'set xtics format "Line1\nLine2" textcolor "black"')
gp.c("plot [-10:10] sin(x),atan(x),cos(atan(x))")

**Comment by dreamonhigh** [comment]
hello Ben.
Yes this works fine.
Thank you very much!
