### ISSUE TITLE
PyGnuplot TypeError: a bytes-like object is required, not 'str' on Python 3.6.1 Windows 7

### ISSUE THREAD

**Issue by jrbrearley** [benschneider/PyGnuplot#5]
Is PyGnuplot supported on  Python 3.6.1 on Windows 7?

Loosely following the example in the online help text, the PyGnuplot.p and PyGnuplot.c functions are getting the error :
  File "C:\WinPython\python-3.6.1.amd64\lib\site-packages\PyGnuplot.py", line 63, in c
    proc.stdin.write(command + '\n')  # \n 'send return'
TypeError: a bytes-like object is required, not 'str'

Yes, Gnuplot 5.2.0 is correctly installed and PATH variable updated for gnuplot/bin

Here is my actual code:

import PyGnuplot
# Set up lists of data to plot.
print ("Setup data for graph")
x = [] ; y = []; z = [] ; w = [];# empty lists
for i in (range (17)):
    x.append(i)
    y.append(i*3)
    z.append(i**2)
    w.append(-i)
print ("x:", x, type(x))
print ("y:",y ,type(y))
print ("z:",z ,type(z))
print ("w:", w, type(w))

# Setup for saving data to disk
import sys
self=sys.argv[0]
import os
file = os.path.basename(self)
(fn, ft) = os.path.splitext(file)
print ("\nself:", self, "file:", file, "fn:", fn, "ft:", ft)
dat_fn = fn+".dat"
fmt="png"
out_fn = fn+"."+fmt
trc_fn = fn+".gnu" ;# save gnuplot commands for debugging
print ("dat_fn:", dat_fn, "fmt:", fmt, "out_fn:", out_fn, "trc_fn:",trc_fn)

# Save data to disk file, 4 values per row, meaning line in file.
print ("\nSave data to:", dat_fn)
rc = PyGnuplot.s([x, y, z, w], filename=dat_fn)
print ("s rc:", rc, type(rc))

# Plot data
import traceback
try:
   rc = PyGnuplot.p(filename=out_fn)
   print ("p rc:", rc, type(rc))
except:
   (x,y,z)=sys.exc_info()
   print("x=",x,"\ny=",y,"\nz=",z)
   traceback.print_exc()

cmd_setup = ""
cmd_plot = 'plot dat_fn u 1:2 w lp'
cmd_cleanup = ""
cmd = cmd_setup+"\n"+cmd_plot+"\n"+cmd_cleanup
print ("gnuplot cmd:", cmd)
# rc = PyGnuplot.c(cmd)
try:
   rc = PyGnuplot.c('plot "tmp.dat" u 1:2 w lp')
   print ("c rc:", rc, type(rc))
except:
   (x,y,z)=sys.exc_info()
   print("x=",x,"\ny=",y,"\nz=",z)
   traceback.print_exc()

Here is the runtime output:

================= RESTART: C:\JOHN_MIS\PY_EX\pygnuplot_ex.py =================
Setup data for graph
x: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16] <class 'list'>
y: [0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48] <class 'list'>
z: [0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256] <class 'list'>
w: [0, -1, -2, -3, -4, -5, -6, -7, -8, -9, -10, -11, -12, -13, -14, -15, -16] <class 'list'>

self: C:\JOHN_MIS\PY_EX\pygnuplot_ex.py file: pygnuplot_ex.py fn: pygnuplot_ex ft: .py
dat_fn: pygnuplot_ex.dat fmt: png out_fn: pygnuplot_ex.png trc_fn: pygnuplot_ex.gnu

Save data to: pygnuplot_ex.dat
s rc: None <class 'NoneType'>
x= <class 'TypeError'> 
y= a bytes-like object is required, not 'str' 
z= <traceback object at 0x0000000003C2CD88>
Traceback (most recent call last):
  File "C:\JOHN_MIS\PY_EX\pygnuplot_ex.py", line 51, in <module>
    rc = PyGnuplot.p(filename=out_fn)
  File "C:\WinPython\python-3.6.1.amd64\lib\site-packages\PyGnuplot.py", line 86, in p
    str(fontsize) + " font 'Calibri';")
  File "C:\WinPython\python-3.6.1.amd64\lib\site-packages\PyGnuplot.py", line 63, in c
    proc.stdin.write(command + '\n')  # \n 'send return'
TypeError: a bytes-like object is required, not 'str'
gnuplot cmd: 
plot dat_fn u 1:2 w lp

x= <class 'TypeError'> 
y= a bytes-like object is required, not 'str' 
z= <traceback object at 0x0000000003C32248>
Traceback (most recent call last):
  File "C:\JOHN_MIS\PY_EX\pygnuplot_ex.py", line 65, in <module>
    rc = PyGnuplot.c('plot "tmp.dat" u 1:2 w lp')
  File "C:\WinPython\python-3.6.1.amd64\lib\site-packages\PyGnuplot.py", line 63, in c
    proc.stdin.write(command + '\n')  # \n 'send return'
TypeError: a bytes-like object is required, not 'str'
>>>

**Comment by benschneider** [comment]
Hi, I noticed this error as well in Python 3+, currently working on that issue.

**Comment by benschneider** [comment]
I pushed a new version which should fix this error. 
try: 'python example.py'

**Comment by jrbrearley** [comment]
Thanks, error fixed.
