### ISSUE TITLE
PyGnuplot no error output, no output file from gnuplot

### ISSUE THREAD

**Issue by jrbrearley** [benschneider/PyGnuplot#6]
Running your example.py as is, there are no error messages, the example.out file is created OK, but NO example.pdf output file is created.

I did some experiments to see what sort of error handling/reporting occurs. The line pg.c("plot 'foo.bar'") generates no errors at all. When you give the same command to a gnuplot terminal window, you get:

gnuplot> plot 'foo.bar'
         warning: Cannot find or open file "foo.bar"
         No data in plot
gnuplot>

My own code sends the following multiple command set as a single line to gnuplot:
set output "pygnuplot_ex.png";set terminal png transparent nocrop enhanced font arial 12 size 400,400;set key autotitle columnhead;set title "Lines Points Example";set xlabel "X-axis Title";set ylabel "Y-axis Title" rotate by 90;set style data linespoints;set xtics rotate by 90;plot "pygnuplot_ex.dat" using 2:xtic(1) , '' using 3 , '' using 4;unset output

When run by PyGnuplot.c, there is no error, but also NO output .png file. The same string pasted into a gnuplot terminal window DOES correctly generate a .png file

**Comment by jrbrearley** [comment]
Just to see  what error info was available, I added some debug code to the .c method to look at the popen object atttributes proc.stdout & proc.stderr. They were always showing None. Hmmm, a silent failure....

**Comment by jrbrearley** [comment]
Today I made a major discovery. The example.py script works fine when I run it from the command line WinPython Command Prompt.exe shell. However, under IDLEX GUI, the same script doesn't produce gnuplot graphic files! The same effect occurs with my own learning test script. Can you confirm this behavior in your environment? If confirmed, I can submit a bug report to the IDLEX development folks.

**Comment by jrbrearley** [comment]
I setup a second Win 7 PC and easily reproduced the issue on the second PC. So I submitted this bug report: https://bugs.python.org/issue31880 We'll see what they say.

**Comment by benschneider** [comment]
Thank you for the help with this.
I am still investigating if I am treating the subprocess wrong somehow.

**Comment by jrbrearley** [comment]
Additonal testing shows that the subprocess.run command will reliably interact directly with gnuplot, either from the IDLEX GUI or the Python terminal window.

import subprocess
def run_cmd(cmd):
   print("run_cmd cmd:", cmd)
   # MUST explicitly ask for stdout, stderr. timeout is in seconds
   p1 = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=20)
   # print("run_cmd p1:", p1, type(p1))
   print("run_cmd p1.stdout:", p1.stdout, type(p1.stdout), p1.stdout.decode("utf-8"))
   print("run_cmd p1.stderr:", p1.stderr, type(p1.stderr), p1.stderr.decode("utf-8"))
   print("run_cmd p1.returncode:", p1.returncode, type(p1.returncode))

cmd = "gnuplot.exe "+self+"_candles.gnu"
run_cmd(cmd)

**Comment by benschneider** [comment]
Thank you very much!
Will test it and see if a more compatible version can be made.

**Comment by benschneider** [comment]
okay I found the thing subprocess that changed between python 2.7 and 3.4+.
stdout does not by default flush the buffer when you send a new line, which caused some problems here.
Just test my new version.

**Comment by jrbrearley** [comment]
Excellent! The flush does the trick. IDLEX GUI now runs your example and my own test code correctly.

    proc.stdin.flush()  # send the command in python 3.4+
