### ISSUE TITLE
PyGnuplot .s restrictions

### ISSUE THREAD

**Issue by jrbrearley** [benschneider/PyGnuplot#7]
The routine PyGnuplot.s for storing data in a file has 2 major restrictions:
1) You cant store any text data. This is useful for putting graph titles in the first row or column of data
2) Data is stored in scientific format, eg -2.044999999999999929e+01, even though the script generated integers.

So when you try to use a series of integers for the X-axis, you get messy results:
![pydot_example](https://user-images.githubusercontent.com/32575796/31785733-247f1728-b4d4-11e7-88fc-b6c16c385e6c.png)

Not sure if there are any long term implications, but the data is also stored with comma separators. Gnuplot documentation does state that whitespace is the default separator. There are options to choose comma or other characters. You may be relying on gnuplot currently being tolerant in its input parsers. Its not obvious that this is guaranteed to stay that way going forward.

**Comment by PanderMusubi** [comment]
I really like the package you have created. Not being able to store text data is a showstopper unfortunately for pie charts, histograms, etc. Could this be fixed, please? The error in Python 3 is:

    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/numpy/lib/npyio.py", line 1215, in savetxt
        fh.write(asbytes(format % tuple(row) + newline))
    TypeError: must be real number, not numpy.str_
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "xxxxx.py", line xx, in <module>
        yyyyy()
      File "zzzzz.py", line zz, in yyyyy
        PyGnuplot.s([x, y])
      File "/usr/local/lib/python3.6/dist-packages/PyGnuplot.py", line 74, in s
        _savetxt(filename, _array(data), delimiter=', ')
      File "/usr/lib/python3/dist-packages/numpy/lib/npyio.py", line 1219, in savetxt
        % (str(X.dtype), format))
    TypeError: Mismatch between array dtype ('<U22') and format specifier ('%.18e, %.18e')

**Comment by benschneider** [comment]
All thats needed is a way to safe not just data but also text into the same file then.
Working on it.

**Comment by jrbrearley** [comment]
Thanks for the fix Ben. I can now put text labels in the data file and make a graph like this:
![pygnuplot_ex](https://user-images.githubusercontent.com/32575796/36737169-6e6bcb2a-1ba8-11e8-8897-11997709ad35.png)

**Comment by PanderMusubi** [comment]
Thanks!
