### ISSUE TITLE
Create Debian package for Debian and Ubuntu

### ISSUE THREAD

**Issue by PanderMusubi** [benschneider/PyGnuplot#9]
Please, create a Debian package for Debian and Ubuntu and/or vote for the packaging process at Ubuntu, see https://bugs.launchpad.net/ubuntu/+bug/1774773

**Comment by benschneider** [comment]
Hi
It seems default ubuntu comes with Python but without the PIP installer. I will have a look into the Debian package options.

 In the meantime the 'install' script file should install it even without PIP.
(Alternatively install it by installing the PIP installer first)

**Comment by PanderMusubi** [comment]
See:
- https://packages.debian.org/source/buster/pygnuplot
- https://packages.ubuntu.com/source/focal/pygnuplot
- https://launchpad.net/ubuntu/+source/pygnuplot
